language: ruby
rvm:
  - 2.0
  - 2.1
  - 2.2
gemfile:
  - test/gemfiles/rails-4.0
  - test/gemfiles/rails-4.1
  - test/gemfiles/rails-4.2

notifications:
  recipients:
    email:
      - cedric@howe.net
  on_success: change
  on_failure: always
